config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :usuarios

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
    validates  :nombres, presence:true,
                    length:{minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)

  if  @usuario.save
    redirect_to @usuario
  else
    render 'new'
 end
end

def show
  @usuario = Usuario.find(params[:id])

  end

def index
  @usuarios = Usuario.all
end




def update
  @usuario = Usuario.find(params[:id])

  if @usuario.update(usuario_params)
    redirect_to @usuario
  else
    render 'edit'
  end
end

def destroy
  @usuario = Usuario.find(params[:id])
  @usuario.destroy

  redirect_to articles_path
end
  private
  def usuario_params
    params.require(:usuario).permit(:nombres, :apellidos, :email, :telefono)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DirectorioUsuarios</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/edit.html.erb
<h1>Editar Usuarios</h1>

<%= form_for :usuario, url: usuario_path(@usuario), method: :patch do |f| %>
  <% if @usuario.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@usuario.errors.count, "error") %> NO se pudo guardar el usuario:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :Nombres %><br>
    <%= f.text_field :nombres %>
  </p>

  <p>
    <%= f.label :Apellidos %><br>
    <%= f.text_field :apellidos %>
  </p>

  <p>
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :Telefono %><br>
    <%= f.text_field :telefono %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listado de Usuarios</h1>

<%= link_to 'Crear nuevo usuario', new_usuario_path %>

<table>
  <tr>
    <th>Nombres</th>
    <th>apellidos</th>
    <th>Email</th>
    <th>Telefono</th>
  </tr>

  <% @usuarios.each do |usuario| %>
    <tr>
      <td><%= usuario.nombres %></td>
      <td><%= usuario.apellidos %></td>
      <td><%= usuario.email %></td>
      <td><%= usuario.telefono %></td>
      <td><%= link_to 'Mostrar', usuarios_path(@usuario) %></td>
     </tr>
  <% end %>
</table>

app/views/usuarios/new.html.erb
<h1>Nuevo Usuario</h1>

<%= form_for :usuario , url: usuarios_path do |f| %>
  <p>
    <%= f.label :Nombres %><br>
    <%= f.text_field :names %>
  </p>

  <p>
    <%= f.label :Apellidos %><br>
    <%= f.text_area :apellidos %>
  </p>

  <p>
    <%= f.label :Email %><br>
    <%= f.text_area :email %>
  </p>

  <p>
    <%= f.label :Telefono %><br>
    <%= f.text_area :telefono %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/usuarios/show.html.erb
<h1>Usuario creado:</h1>

<%= form_for :usuario , url: usuarios_path do |f| %>
<p>
  <strong>Nombres:</strong>
  <%= @usuario.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @usuario.telefono %>
</p>
<% end %>
<%= link_to 'Atras', usuarios_path %>

app/views/welcome/index.html.erb
<h1>Bienvenido a Directorio De Usuarios</h1>
<p>Esta es una aplicacion de prueba que administra Usuarios</p>

<%= link_to 'Mis Usuarios', controller: 'usuarios' %>